### ISSUE TITLE
changing-organization-url-in-schema - does not update Organization URL as expected

### ISSUE THREAD

**Issue by parkerauk** [Yoast/developer-docs#143]
* [y ] I've read and understood the [contribution guidelines](https://github.com/Yoast/developer-docs/blob/trunk/.github/CONTRIBUTING.md).
* [ y] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of the issue

I have a website with five child sites, that reflect virtual parts of the business with a distinct customer focus. ie Not separate legal entities, not local businesses, not departments etc.   All sites have to be set as Organization as they are not People related.
There is only one organization and should only be one organization across all sites:

main site  https://www.site    (Organization)
sub site 1 https://www.site/GRC/ (Site for a virtual-part of our Organization)
sub site 2 https://www.site/2-5/ (etc)

With Yoast plugin I get 6 different @IDs for Organization (one per site). I only want one.

I expected this to be resolved by deploying the patch listed here: https://developer.yoast.com/customization/local-seo/changing-organization-url-in-schema/

I have applied via functions.php and tested by creating new pages, however SEO Organization URL remains unchanged. 
![image](https://user-images.githubusercontent.com/38226478/131646826-de921530-61ed-4e0d-8ca3-d5aebb7040b2.png)
See Image

Instead however I have noticed that the link to Schema settings took the new URL instead. See very bottom of image. /GRC is missing from URL

![image](https://user-images.githubusercontent.com/38226478/131646290-3f3bb7dc-e3fe-42cd-b3aa-2f1cecc12a4d.png)

Could someone please tell me what I am doing wrong, or fix the description.   Thanks in advance.

Using Free version of Yoast SEO
WP & Yoast, current release
PHP 7.3

![image](https://user-images.githubusercontent.com/38226478/131647949-b6076cbe-2389-477b-99b8-f7a80d068662.png)

**Comment by jdevalk** [comment]
The filter you're using is actually for our Local SEO plugin. In this case you have to update the `Organization` piece, for which you could change use the `wpseo_schema_organization` filter. Related examples can be found here:

https://developer.yoast.com/features/schema/api/#change-a-graph-pieces-data
