### ISSUE TITLE
MyYoast subscription api client links are broken

### ISSUE THREAD

**Issue by david-robinson-practiceweb** [Yoast/developer-docs#149]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/developer-docs/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of the issue

On docs/customization/myyoast/apis/subscription-api.md (https://developer.yoast.com/customization/myyoast/apis/subscription-api) there are links to client libs for PHP and js. All of these links are 404ing e.g  https://github.com/Yoast/subscription-api-php-client
Could you please provide the correct links or if they are no longer supported then could you update the documentation accordingly.
Since the doc page mentions that the code was generated via swagger it would be useful to have a direct link to the raw spec as well.

**Comment by jdevalk** [comment]
Thanks for noticing, sorry for not seeing this sooner. I've just opened up both repositories.
