### ISSUE TITLE
Mention the Enhanced_Data_Presenter in the documentation

### ISSUE THREAD

**Issue by nanu-c** [Yoast/developer-docs#153]
## Is your feature request related to a problem? Please describe.
I don't want to have the the author in the opengraph. Currently it's in
```
<meta name="twitter:label1" content="Written by" />
	<meta name="twitter:data1" content="admin" />
	<meta name="twitter:label2" content="Estimated reading time" />
	<meta name="twitter:data2" content="6 minutes" />
```
The label2 is okey for me. Then i searched the documentation at https://developer.yoast.com/customization/apis/metadata-api/ for any mention of that `twitter:label`, there is none.

Then in the code it's part of slack enhanced data presenter.

https://github.com/Yoast/wordpress-seo/blob/5c4cb165764c5dac0e222a6483fa18b209cc262c/src/presenters/slack/enhanced-data-presenter.php#L30

## Describe the solution you'd like
Make it optional or mention the slack thing in the documentation.

## Why do you think this feature is something we should consider for the Yoast SEO plugins?
Because customers want to change everything and at least there should be *all* presenters at https://developer.yoast.com/customization/apis/metadata-api/

**Comment by Djennez** [comment]
Moved to the developer docs repo.

**Comment by jdevalk** [comment]
I think we actually do: https://developer.yoast.com/customization/yoast-seo/changing-enhanced-slack-sharing/
