### ISSUE TITLE
Don't create the Yoast folder in Documents.

### ISSUE THREAD

**Issue by hdvos** [Yoast/developer-docs#161]
https://github.com/Yoast/developer-docs/blob/fc676dfa61d7dcb626338359e5cb926188f1f665/docs/development/environment/setup.md?plain=1#L17

If (on mac) you create the `Yoast` folder in `Documents`, this wil throw a `stale NFS file handle` Error. 

This documentation is probably from before the switch from Docker Desktop to Rancher.
I am not entirely sure on the best phrasing, but would suggest something along the lines of:

"Generally speaking, we advise people to create a `~/Projects/Yoast` (Note don't create a Yoast folder in `Documents`/`Desktop` or `Downloads`; this will likely cause an error) folder to keep all things together. After this, you have two flavors "

props to @mhkuu

**Comment by jdevalk** [comment]
Fixing in new repo.
