### ISSUE TITLE
Add a handful of specific examples in "To add or remove graph pieces"

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/developer-docs#26]
See https://developer.yoast.com/features/schema/api.

Adding new pieces is one of the primary use-cases, but there are no examples here (and the referenced example is on a different page).

We should add a handful of examples here which utilize `$context`.

**Comment by audiovisuel-uqam** [comment]
Also, on the page [#to-add-or-remove-graph-pieces](https://developer.yoast.com/features/schema/api/#to-add-or-remove-graph-pieces) 
>  deeper examples can be found here on Github.

leads to a 404

**Comment by jcomack** [comment]
The issue mentioned by @audiovisuel-uqam will be fixed once https://github.com/Yoast/developer-docs/pull/43 is merged

**Comment by jcomack** [comment]
Discussed with @jono-alderson: There's already [a link to one example](https://developer.yoast.com/features/schema/integration-guidelines#an-example-use-case) and another to more on GitHub, so adding even more doesn't add much value. I will therefor be closing this issue.
