### ISSUE TITLE
Add examples to metadata API doc

### ISSUE THREAD

**Issue by jono-alderson** [Yoast/developer-docs#60]
The [Metadata API page](https://developer.yoast.com/customization/apis/metadata-api) has three 'gaps' which need filling:

At the end of the current content:
- An example of how to modify an existing tag's behaviour
- An example of how to remove an existing tag

To be placed somewhere sensible:
- One or more examples of using the '3 public properties' referenced.

**Comment by jcomack** [comment]
Moved this issue over to Jira
