### ISSUE TITLE
Error Message: wpseo_premium_post_redirect_slug_change is deprecated since version YoastSEO Premium 12.9.0!

### ISSUE THREAD

**Issue by jimmyddalton** [Yoast/developer-docs#73]
Changed the slug on a post, saved, then updated post. This error message appears. Trying to disable Yoast Redirects.

![image](https://user-images.githubusercontent.com/45102/86818945-a23a5200-c04c-11ea-8a5e-b5afe283af28.png)

![image](https://user-images.githubusercontent.com/45102/86818784-6901e200-c04c-11ea-87b7-c19061617146.png)

**Comment by jcomack** [comment]
Hey @jimmyddalton thanks for reporting this! Your report sparked an investigation into these filters and we're looking into it.
I'll update this issue as soon as possible.

**Comment by lkraav** [comment]
Indeed, it seems like https://developer.yoast.com/customization/yoast-seo-premium/disabling-automatic-redirects-notifications/ should be updated for new filter names?

**Comment by jcomack** [comment]
@lkraav Correct. I've reported this issue internally, but will have to check on its current status.
