### ISSUE TITLE
 not removing the og:locale tag as expected

### ISSUE THREAD

**Issue by mikey79** [Yoast/developer-docs#75]
* [x ] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [ x] I've searched for any related issues and avoided creating a duplicate issue.

Hi there,

as confirmed by the Yoast team here https://wordpress.org/support/topic/removing-oglocale-doesnt-work/#post-13139938 I found an issue:

The removal of og:locale doesn't work anymore like described here: https://developer.yoast.com/features/opengraph/api/changing-og-locale-output/.

Yoast version 14.5 doesn't support the mentioned removal method of og:locale.

The issue and the facts that guided to the issue are mentioned on the above linked wordpress-thread.

I'd really appreciate if you could have a look and find a solution for removing og:locale with Yoast 14.5.

Best
mikey

### Please describe what you expected to happen and why.

Please find a solution - because it's simply impossible to remove og:locale with the method described here: https://developer.yoast.com/features/opengraph/api/changing-og-locale-output/.

### How can we reproduce this behavior?
1. Use the below mentioned technical info and try to remove og:locale tag like described in the official Yoast tutorial: https://developer.yoast.com/features/opengraph/api/changing-og-locale-output/ - it will not work.

### Technical info
* WordPress version: WordPress 5.4.2
* Yoast SEO version: Yoast 14.5

* If relevant, which editor is affected (or editors): 
- [ ] Classic Editor
- [ ] Gutenberg
- [ ] Classic Editor plugin

* Which browser is affected (or browsers): 
- [ ] IE11
- [ ] Edge
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

* Relevant plugins in case of a bug:

* Tested with theme: twenty twenty as well as with custom theme - issue stays the same ...

**Comment by jono-alderson** [comment]
Assigned to @jcomack to do the honours of updating the docs.
