### ISSUE TITLE
wpseo_opengraph_image_size Filter Documentation is Incorrect

### ISSUE THREAD

**Issue by tjdunklee** [Yoast/developer-docs#79]
* [x] I've read and understood the [contribution guidelines](https://github.com/Yoast/wordpress-seo/blob/trunk/.github/CONTRIBUTING.md).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### Please give us a description of what happened.
I was trying to use the front-end filter for changing the size of the open graph image. The filter is called "wpseo_opengraph_image_size" and it is documented on this page:

https://yoast.com/wordpress/plugins/seo/api/

I couldn't figure out why the filter wasn't working for a while until I started diving into the source code of Yoast SEO. It turns out the filter is expecting a string and not an integer like the documentation mentions. Also, it would be nice if the documentation explained that the string is one of the set Wordpress image sizes.

### Please describe what you expected to happen and why.
I would expect the documentation of the filter to be correct and give a little more detailed explanation.

### How can we reproduce this behavior?
1. Add a filter to change the open graph image size
2. Return an integer

### Technical info
* WordPress version: 4.9.6
* Yoast SEO version: 7.6.1
* Relevant plugins in case of a bug:
* Tested with theme: TwentySeventeen

**Comment by jcomack** [comment]
I completely forgot to link this issue when I submitted https://github.com/Yoast/developer-docs/pull/84

The description should now be better / explain better how to use the filter.
